WORKSPACE_ID = "FusionSolidEnvironment"
PRIMARY_PANEL_ID = "SolidModifyPanel"
PANEL_IDS = [
    "SolidModifyPanel",
    "SolidToolsPanel",
    "SolidCreatePanel",
    "SolidScriptsAddinsPanel",
]
CUSTOM_TAB_ID = "SolidTab"
CUSTOM_PANEL_ID = "DIYGarageCut_DIYGarageCutPropertiesAddin_Panel"
CUSTOM_PANEL_NAME = "DIY Garage Cut"
COMMAND_ID = "DIYGarageCut_DIYGarageCutPropertiesAddin_PropertiesCommand"
COMMAND_NAME = "DIYGC Eigenschaften"
COMMAND_TOOLTIP = "Material und Fräszulage für einen Body setzen."
COMMAND_RESOURCES = "./Resources"

ATTRIBUTE_GROUP = "DIYGarageCut.part_metadata"
ATTR_KEY_MATERIAL_ID = "material_id"
ATTR_KEY_TRIM_ALLOWANCE_MM = "trim_allowance_mm"
ATTR_KEY_GRAIN_DIRECTION = "grain_direction"
ATTR_KEY_FRONT_REFERENCE = "front_reference"
ATTR_KEY_EDGE_FRONT = "edge_front"
ATTR_KEY_EDGE_BACK = "edge_back"
ATTR_KEY_EDGE_LEFT = "edge_left"
ATTR_KEY_EDGE_RIGHT = "edge_right"
ATTR_KEY_SURFACE_TOP = "surface_top"
ATTR_KEY_SURFACE_BOTTOM = "surface_bottom"
ATTR_KEY_EDGE_FRONT_CUSTOM_TEXT = "edge_front_custom_text"
ATTR_KEY_EDGE_BACK_CUSTOM_TEXT = "edge_back_custom_text"
ATTR_KEY_EDGE_LEFT_CUSTOM_TEXT = "edge_left_custom_text"
ATTR_KEY_EDGE_RIGHT_CUSTOM_TEXT = "edge_right_custom_text"
ATTR_KEY_SURFACE_TOP_CUSTOM_TEXT = "surface_top_custom_text"
ATTR_KEY_SURFACE_BOTTOM_CUSTOM_TEXT = "surface_bottom_custom_text"
ATTR_KEY_NOTES = "notes"
ATTR_KEY_EXCLUDE_FROM_EXPORT = "exclude_from_export"
CUSTOM_TEXT_VALUE = "__text__"

TYPE_FIELD_TRIM_ALLOWANCE = "sheet_default_trim_allowance"
TYPE_FIELD_HAS_GRAIN = "sheet_has_grain"
TYPE_FIELD_DEFAULT_GRAIN_DIRECTION = "sheet_default_grain_direction"
TYPE_FIELD_EDGE_THICKNESS = "edge_thickness"

_INPUT_BODY = "diygc_body_selection"
_INPUT_SIZE = "diygc_size"
_INPUT_FILTER_TYPE = "diygc_filter_type"
_INPUT_MATERIAL = "diygc_material"
_INPUT_TRIM_ALLOWANCE = "diygc_trim_allowance_mm"
_INPUT_GRAIN_DIRECTION = "diygc_grain_direction"
_INPUT_EDGES_ENABLED = "diygc_edges_enabled"
_INPUT_FRONT_FACE = "diygc_front_face"
_INPUT_EDGES_HEADER = "diygc_edges_header"
_INPUT_EDGE_MODE = "diygc_edge_mode"
_INPUT_EDGE_ALL = "diygc_edge_all"
_INPUT_ALL_SURFACE = "diygc_all_surface"
_INPUT_ALL_SURFACE_TEXT = "diygc_all_surface_text"
_INPUT_EDGE_FRONT_ENABLED = "diygc_edge_front_enabled"
_INPUT_EDGE_FRONT = "diygc_edge_front"
_INPUT_EDGE_FRONT_TEXT = "diygc_edge_front_text"
_INPUT_EDGE_BACK_ENABLED = "diygc_edge_back_enabled"
_INPUT_EDGE_BACK = "diygc_edge_back"
_INPUT_EDGE_BACK_TEXT = "diygc_edge_back_text"
_INPUT_EDGE_LEFT_ENABLED = "diygc_edge_left_enabled"
_INPUT_EDGE_LEFT = "diygc_edge_left"
_INPUT_EDGE_LEFT_TEXT = "diygc_edge_left_text"
_INPUT_EDGE_RIGHT_ENABLED = "diygc_edge_right_enabled"
_INPUT_EDGE_RIGHT = "diygc_edge_right"
_INPUT_EDGE_RIGHT_TEXT = "diygc_edge_right_text"
_INPUT_SURFACE_ALL_TEXT = "diygc_surface_all_text"
_INPUT_TOP_ENABLED = "diygc_top_enabled"
_INPUT_TOP_SURFACE = "diygc_top_surface"
_INPUT_TOP_SURFACE_TEXT = "diygc_top_surface_text"
_INPUT_BOTTOM_ENABLED = "diygc_bottom_enabled"
_INPUT_BOTTOM_SURFACE = "diygc_bottom_surface"
_INPUT_BOTTOM_SURFACE_TEXT = "diygc_bottom_surface_text"
_INPUT_SWAP_LEFT_RIGHT = "diygc_swap_left_right"
_INPUT_SWAP_SURFACES = "diygc_swap_surfaces"
_INPUT_EXCLUDE_FROM_EXPORT = "diygc_exclude_from_export"
_INPUT_NOTES_HEADER = "diygc_notes_header"
_INPUT_NOTES = "diygc_notes"
_INPUT_APPLY = "diygc_apply"

__all__ = [name for name in globals() if name.isupper() or name.startswith("_INPUT_")]
